### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dol4iua** [PluginBugs/Issues-ServerBooster#58]
after i remove serverbooster ,  some mobs have lost intelligence, how to fix it?
https://cdn.discordapp.com/attachments/1000531193474850919/1000531355735707648/2022-07-23_13-33-36.mp4

**Comment by LoneDev6** [comment]
which ServerBooster version did you install when you first bought the plugin? 

The old version of ServerBooster used to remove AI of mobs, then re-add it on chunk load.
The issue is that if you uninstalled the plugin your mobs might not have their AI re-added.

The new version of the plugin doesn't remove AI of mobs, it uses another method.

You probably have to keep the plugin installed in order to let it re-add AI of frozen mobs which were frozen with an old version of ServerBooster.
