### ISSUE TITLE
[BUG] Console Spam Task #71 for ServerBooster v1.1.3

### ISSUE THREAD

**Issue by Cheu3172** [PluginBugs/Issues-ServerBooster#62]
Constant spamming of the console, Minecraft-version 1.19.2; PurpurMc.

https://pastebin.com/VZmE8Vdy

**Comment by Tenet70** [comment]
Exact same error here using latest purpur.

**Comment by CitizenPrayer** [comment]
I'm experiencing a similar error. Every time I've seen this error on this GitHub page the Dev has suggested downloading the latest Paper/PurperMC version, and that solves it.

Can I dare to say, Dev, fix your code, please. Having the latest and greatest version of someone else's software shouldn't break your code, and if it does, it's because your code is too strictly structuring itself. (i.e. it doesn't make sense that someone else's update should ruin your code. If it worked on the previous version, and they merely updated their versioning, then you fix you)

**Comment by LoneDev6** [comment]
> Can I dare to say, Dev, fix your code, please. Having the latest and greatest version of someone else's software shouldn't break your code, and if it does,

This is not how it works.
The game structure changes a lot between updates, it's impossible to make the plugin automatically magically work on every future version without updating it.

**Comment by LoneDev6** [comment]
>  yet your plugin still throws consistent error

Make a new issue report and post them.
The plugin was currently tested on 1.19.2 Paper and works fine.

> I would beg to differ;

This plugin uses internal Minecraft code which changes a lot during updates.
The code cannot magically work automatically on each game build, I need always to check what changed between versions and update accordingly.

The plugin has an implementation for each one of the Minecraft versions available.
Do you really think that there is a single magical code which can work on any version?
I have to code the plugin for each version of the game.

![image](https://user-images.githubusercontent.com/27242001/195120399-363358f4-64bb-40f2-b771-82fece5ded13.png)

Anyway if you're not satisfied with how I manage my plugin you can ask for a refund and look for an alternative.
Have a nice day
